import { createServerSupabase } from "@/lib/supabase/server";
export const dynamic="force-dynamic";
function money(v:number){return `$${v.toFixed(2)}`}
export default async function OverviewPage(){
 const supabase=createServerSupabase(); const now=new Date(); const start=new Date(now); start.setHours(0,0,0,0); const end=new Date(start); end.setDate(end.getDate()+1);
 const [{data:restaurant},{data:hours},{data:todayOrders},{data:recentOrders},{data:upcomingReservations}]=await Promise.all([
  supabase.from("restaurants").select("name,timezone").limit(1).single(),
  supabase.from("restaurant_hours").select("day_of_week,opens_at,closes_at,is_closed").order("day_of_week"),
  supabase.from("orders").select("id,status,total,fulfillment_type").gte("created_at",start.toISOString()).lt("created_at",end.toISOString()),
  supabase.from("orders").select("id,order_number,customer_name,fulfillment_type,total,status,created_at").order("created_at",{ascending:false}).limit(6),
  supabase.from("reservations").select("id,reservation_number,customer_name,party_size,requested_date,requested_time,status").gte("requested_date",now.toISOString().slice(0,10)).order("requested_date").order("requested_time").limit(6)
 ]);
 const day=now.getDay(); const h=hours?.find(x=>x.day_of_week===day); const minutes=now.getHours()*60+now.getMinutes(); const openMinutes=h?.opens_at?Number(h.opens_at.slice(0,2))*60+Number(h.opens_at.slice(3,5)):0; const closeMinutes=h?.closes_at?Number(h.closes_at.slice(0,2))*60+Number(h.closes_at.slice(3,5)):0; const isOpen=!!h&&!h.is_closed&&minutes>=openMinutes&&minutes<closeMinutes;
 const orders=todayOrders??[]; const revenue=orders.reduce((s,o)=>s+Number(o.total||0),0); const pending=orders.filter(o=>o.status==="pending").length; const deliveries=orders.filter(o=>o.fulfillment_type==="delivery"&&!['completed','cancelled'].includes(o.status)).length; const pendingReservations=(upcomingReservations??[]).filter(r=>r.status==="pending").length;
 const metrics=[{label:"Orders today",value:String(orders.length),note:"Live orders"},{label:"Revenue today",value:money(revenue),note:"From order totals"},{label:"Pending approvals",value:String(pending+pendingReservations),note:"Orders + reservation requests"},{label:"Upcoming reservations",value:String((upcomingReservations??[]).length),note:"Next requests"},{label:"Active deliveries",value:String(deliveries),note:"Not completed"},{label:"AI calls today",value:"—",note:"Retell not connected"}];
 return <div className="space-y-8"><section className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-blue-600">Command center</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-950">Good to see you.</h1><p className="mt-2 text-slate-500">Live operations for {restaurant?.name??"Restaurant"}.</p></div><div className="flex items-center gap-3 rounded-xl border border-slate-200 bg-white px-4 py-3 shadow-sm"><span className={`h-2.5 w-2.5 rounded-full ${isOpen?"bg-emerald-500":"bg-slate-400"}`}/><div><div className="text-xs font-semibold text-slate-500">RESTAURANT STATUS</div><div className="text-sm font-bold text-slate-950">{isOpen?"OPEN":"CLOSED"}</div></div><div className="border-l border-slate-200 pl-3 text-xs text-slate-500">{now.toLocaleString([], {dateStyle:"medium",timeStyle:"short"})}</div></div></section>
 <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6">{metrics.map(m=><div key={m.label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{m.label}</p><p className="mt-3 text-2xl font-bold text-slate-950">{m.value}</p><p className="mt-1 text-xs text-slate-400">{m.note}</p></div>)}</section>
 <section className="rounded-2xl border border-blue-100 bg-blue-50/60 p-5"><div className="flex items-start gap-3"><div className="mt-0.5 rounded-lg bg-white p-2 text-blue-600 shadow-sm">!</div><div><h2 className="font-semibold text-slate-950">Attention required</h2>{pending||pendingReservations?<p className="mt-1 text-sm text-slate-600">{pending} new order{pending===1?"":"s"} and {pendingReservations} reservation request{pendingReservations===1?"":"s"} are waiting for staff action.</p>:<p className="mt-1 text-sm text-slate-600">Everything is under control. No pending staff actions.</p>}</div></div></section>
 <div className="grid gap-6 xl:grid-cols-[1.4fr_1fr]"><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-200 px-5 py-4"><div><h2 className="font-semibold">Recent orders</h2><p className="mt-0.5 text-xs text-slate-500">Latest activity from Supabase</p></div><a href="/orders" className="text-sm font-semibold text-blue-600">View all</a></div>{recentOrders?.length?<div className="divide-y divide-slate-100">{recentOrders.map(o=><div key={o.id} className="flex items-center justify-between gap-4 px-5 py-4"><div><div className="font-medium">#{o.order_number} · {o.customer_name}</div><div className="mt-1 text-xs capitalize text-slate-500">{o.fulfillment_type.replace("_"," ")} · {new Date(o.created_at).toLocaleTimeString([], {hour:"numeric",minute:"2-digit"})}</div></div><div className="text-right"><div className="font-semibold">{money(Number(o.total))}</div><div className="mt-1 text-xs capitalize text-slate-500">{o.status}</div></div></div>)}</div>:<div className="p-10 text-center text-sm text-slate-500">No orders yet.</div>}</section>
 <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-200 px-5 py-4"><div><h2 className="font-semibold">Upcoming reservations</h2><p className="mt-0.5 text-xs text-slate-500">Next scheduled requests</p></div><a href="/reservations" className="text-sm font-semibold text-blue-600">View all</a></div>{upcomingReservations?.length?<div className="divide-y divide-slate-100">{upcomingReservations.map(r=><div key={r.id} className="px-5 py-4"><div className="flex justify-between gap-4"><div className="font-medium">{r.customer_name}</div><span className="rounded-full bg-slate-100 px-2 py-1 text-[11px] font-semibold capitalize">{r.status}</span></div><div className="mt-1 text-xs text-slate-500">Party of {r.party_size} · {r.requested_date} at {String(r.requested_time).slice(0,5)}</div></div>)}</div>:<div className="p-10 text-center text-sm text-slate-500">No upcoming reservations.</div>}</section></div></div>;
}
