import { createServerSupabase } from "@/lib/supabase/server";
export const dynamic = "force-dynamic";

export default async function SettingsPage() {
  const s = createServerSupabase();
  const [{ data: r }, { data: l }, { data: h }] = await Promise.all([
    s.from("restaurants").select("name,phone,email,timezone,max_online_party_size,logo_url").limit(1).single(),
    s.from("restaurant_locations").select("name,address_line1,city,province,postal_code").eq("is_active", true).limit(1).single(),
    s.from("restaurant_hours").select("day_of_week,opens_at,closes_at,is_closed").order("day_of_week"),
  ]);
  const { data: restaurantIdRow } = await s.from("restaurants").select("id").limit(1).single();
  const { data: settings } = await s.from("restaurant_settings").select("*").eq("restaurant_id", restaurantIdRow?.id ?? "").single();
  const days = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
  const Section = ({ title, children }: { title: string; children: React.ReactNode }) => <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-semibold">{title}</h2><div className="mt-4">{children}</div></section>;
  return <div className="space-y-6">
    <div><p className="text-sm font-semibold text-blue-600">Configuration</p><h1 className="mt-1 text-3xl font-bold">Settings</h1><p className="mt-2 text-slate-500">Operational configuration is read from the active restaurant record and Supabase settings.</p></div>
    <div className="grid gap-6 lg:grid-cols-2">
      <Section title="Restaurant"><dl className="grid gap-4 text-sm sm:grid-cols-2"><div><dt className="text-slate-400">Name</dt><dd className="mt-1 font-medium">{r?.name}</dd></div><div><dt className="text-slate-400">Phone</dt><dd className="mt-1 font-medium">{r?.phone || "Not configured"}</dd></div><div><dt className="text-slate-400">Email</dt><dd className="mt-1 font-medium">{r?.email || "Not configured"}</dd></div><div><dt className="text-slate-400">Timezone</dt><dd className="mt-1 font-medium">{r?.timezone || "Not configured"}</dd></div><div><dt className="text-slate-400">Online party size</dt><dd className="mt-1 font-medium">{r?.max_online_party_size ?? "Not configured"}</dd></div></dl></Section>
      <Section title="Hours"><div className="space-y-2 text-sm">{h?.map(x => <div key={x.day_of_week} className="flex justify-between"><span>{days[x.day_of_week]}</span><span className="text-slate-500">{x.is_closed ? "Closed" : `${x.opens_at?.slice(0, 5)} – ${x.closes_at?.slice(0, 5)}`}</span></div>)}</div></Section>
      <Section title="Orders"><dl className="grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-slate-400">Pickup</dt><dd className="mt-1 font-medium">{settings?.pickup_enabled ? "Enabled" : "Disabled"}</dd></div><div><dt className="text-slate-400">Delivery</dt><dd className="mt-1 font-medium">{settings?.delivery_enabled ? "Enabled" : "Disabled"}</dd></div><div><dt className="text-slate-400">Dine-in</dt><dd className="mt-1 font-medium">{settings?.dine_in_enabled ? "Enabled" : "Disabled"}</dd></div><div><dt className="text-slate-400">Scheduled orders</dt><dd className="mt-1 font-medium">{settings?.scheduled_orders_enabled ? "Enabled" : "Disabled"}</dd></div><div><dt className="text-slate-400">Large-order approval</dt><dd className="mt-1 font-medium">${Number(settings?.large_order_approval_threshold ?? 0).toFixed(2)}</dd></div></dl></Section>
      <Section title="Reservations"><dl className="grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-slate-400">Enabled</dt><dd className="mt-1 font-medium">{settings?.reservations_enabled ? "Yes" : "No"}</dd></div><div><dt className="text-slate-400">Automatic confirmation</dt><dd className="mt-1 font-medium">{settings?.reservations_auto_confirm ? "Enabled" : "Manual"}</dd></div><div><dt className="text-slate-400">Max auto-confirm party</dt><dd className="mt-1 font-medium">{settings?.reservations_max_auto_party_size ?? "Not configured"}</dd></div><div><dt className="text-slate-400">Capacity</dt><dd className="mt-1 font-medium">{settings?.reservation_capacity ?? "Not configured"}</dd></div></dl></Section>
      <Section title="Delivery"><dl className="grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-slate-400">Radius</dt><dd className="mt-1 font-medium">{settings?.delivery_radius_km == null ? "Not configured" : `${settings.delivery_radius_km} km`}</dd></div><div><dt className="text-slate-400">Minimum order</dt><dd className="mt-1 font-medium">${Number(settings?.delivery_minimum_order ?? 0).toFixed(2)}</dd></div><div><dt className="text-slate-400">Free delivery threshold</dt><dd className="mt-1 font-medium">{settings?.free_delivery_threshold == null ? "Not configured" : `$${Number(settings.free_delivery_threshold).toFixed(2)}`}</dd></div><div className="sm:col-span-2"><dt className="text-slate-400">Distance pricing</dt><dd className="mt-1 font-medium">{Array.isArray(settings?.delivery_distance_pricing) && settings.delivery_distance_pricing.length ? "Configured" : "Not configured"}</dd></div></dl><p className="mt-3 text-xs text-slate-500">No mapping service is connected yet. The dashboard will not invent distance or delivery calculations.</p></Section>
      <Section title="AI foundation"><div className="rounded-xl border border-dashed border-slate-300 p-4 text-sm"><div className="font-medium">Retell integration pending</div><p className="mt-1 text-slate-500">AI configuration is stored as a backend foundation only. Retell is not connected and no fake call controls are exposed.</p></div></Section>
      <Section title="Notifications"><dl className="grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-slate-400">Notifications</dt><dd className="mt-1 font-medium">{settings?.notifications_enabled ? "Enabled" : "Disabled"}</dd></div><div><dt className="text-slate-400">Sound</dt><dd className="mt-1 font-medium">{settings?.notification_sound_enabled ? "Enabled" : "Disabled"}</dd></div></dl><p className="mt-3 text-xs text-slate-500">Supabase Realtime order and reservation subscriptions are protected by dashboard authentication and database RLS.</p></Section>
    </div>
  </div>;
}
